name: Deploy to test.seedao.xyz

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Setup Node
       uses: actions/setup-node@v2
       with:
         node-version: '16.17.0'

     - name: Compile
       env:
         CI: false
       run: |
         yarn;
         yarn build;

     - name: Pushes to another repository
       run: |
         git clone --single-branch --branch "master" "https://xrdavies:${{ secrets.PERSONAL_TOKEN }}@github.com/SeeDAO-OpenSource/test.seedao.xyz.git";
         cd test.seedao.xyz;
         git config --global user.name dev;
         git config --global user.email dev@seedao.xyz;
         rm -rf *
         cp -R ../build/* .;
         echo "test.seedao.xyz" > CNAME
         git add .;
         git status;
         git commit -m "deploy";
         git status;
         git push "https://xrdavies:${{ secrets.PERSONAL_TOKEN }}@github.com/SeeDAO-OpenSource/test.seedao.xyz.git" --set-upstream master
